global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets:
            - alert_manager:9093

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: cadvisor
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: node_exporter
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "kong_gateway"
    scrape_interval: 5s
    scrape_timeout: 2s
    honor_labels: true
    static_configs:
      - targets: ["ldi-gateway-dev_kong:8001"]
    metrics_path: /metrics
